In [1]:
import pandas as pd
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
# считываем и сохраняем в df исходный файл
data = pd.read_csv('games.csv')

In [3]:
data

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,NaN,NaN,NaN
...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Critic_Score     8137 non-null   float64
 5   User_Score       10015 non-null  object
 6   Rating           9950 non-null   object
dtypes: float64(2), object(5)
memory usage: 914.4+ KB

В данном случае нам не принципиально кол-во записей для создания примера интерактивных графиков в dash (python). Поэтому просто удалим все записи с пропусками.

In [5]:
# удаление строк с NaN значениями
data = data.dropna()
data

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,76.0,8,E
2,Mario Kart Wii,Wii,2008.0,Racing,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,80.0,8,E
6,New Super Mario Bros.,DS,2006.0,Platform,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,58.0,6.6,E
...,...,...,...,...,...,...,...
16699,Planet Monsters,GBA,2001.0,Action,67.0,tbd,E
16700,Breach,PC,2011.0,Shooter,61.0,5.8,T
16701,Bust-A-Move 3000,GC,2003.0,Puzzle,53.0,tbd,E
16702,Mega Brain Boost,DS,2008.0,Puzzle,48.0,tbd,E
16706,STORM: Frontline Nation,PC,2011.0,Strategy,60.0,7.2,E10+

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7878 entries, 0 to 16706
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             7878 non-null   object
 1   Platform         7878 non-null   object
 2   Year_of_Release  7878 non-null   float64
 3   Genre            7878 non-null   object
 4   Critic_Score     7878 non-null   float64
 5   User_Score       7878 non-null   object
 6   Rating           7878 non-null   object
dtypes: float64(2), object(5)
memory usage: 492.4+ KB

Удалим строки с tbd значениями.  
PS - tbd это аббревиатура to be decided / to be determined

In [7]:
# удаление строк с tbd значениями
data = data[data['User_Score'] != 'tbd']
data

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,76.0,8,E
2,Mario Kart Wii,Wii,2008.0,Racing,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,80.0,8,E
6,New Super Mario Bros.,DS,2006.0,Platform,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,58.0,6.6,E
...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,GBA,2001.0,Action,46.0,2.4,E
16677,Mortal Kombat: Deadly Alliance,GBA,2002.0,Fighting,81.0,8.8,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,80.0,7.6,M
16700,Breach,PC,2011.0,Shooter,61.0,5.8,T
16706,STORM: Frontline Nation,PC,2011.0,Strategy,60.0,7.2,E10+

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6826 entries, 0 to 16706
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6826 non-null   object
 1   Platform         6826 non-null   object
 2   Year_of_Release  6826 non-null   float64
 3   Genre            6826 non-null   object
 4   Critic_Score     6826 non-null   float64
 5   User_Score       6826 non-null   object
 6   Rating           6826 non-null   object
dtypes: float64(2), object(5)
memory usage: 426.6+ KB

Тип данных у года - float, преобразуем в int

In [9]:
data['Year_of_Release']

0        2006.0
2        2008.0
3        2009.0
6        2006.0
7        2006.0
          ...
16667    2001.0
16677    2002.0
16696    2014.0
16700    2011.0
16706    2011.0
Name: Year_of_Release, Length: 6826, dtype: float64

In [10]:
data['Year_of_Release'] = data['Year_of_Release'].astype(int) # перевод из float в тип int

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6826 entries, 0 to 16706
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6826 non-null   object
 1   Platform         6826 non-null   object
 2   Year_of_Release  6826 non-null   int32
 3   Genre            6826 non-null   object
 4   Critic_Score     6826 non-null   float64
 5   User_Score       6826 non-null   object
 6   Rating           6826 non-null   object
dtypes: float64(1), int32(1), object(5)
memory usage: 400.0+ KB

In [12]:
data.sample(10)

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
16117,Ship Simulator 2008,PC,2007,Simulation,62.0,6.6,E
10027,Disney Art Academy,3DS,2016,Action,72.0,6.8,E
15776,NBA 07,PS2,2006,Sports,63.0,6.8,E
283,Madden NFL 2003,PS2,2002,Sports,95.0,7.7,E
9462,Disney's Kim Possible: Kimmunicator,DS,2005,Platform,61.0,7.5,E
2280,NBA 2K14,XOne,2013,Sports,86.0,5.7,E
8217,Winning Eleven: Pro Evolution Soccer 2007,DS,2006,Sports,63.0,7.9,E
15618,Guitar Hero III: Legends of Rock,PC,2007,Misc,79.0,7.2,T
797,Dying Light,PS4,2015,Action,74.0,7.9,M
3205,Angry Birds Trilogy,3DS,2012,Action,62.0,4.6,E

Оставим только записи с годом >= 2000

In [13]:
data = data[data['Year_of_Release'] >= 2000]

In [15]:
data['User_Score'] = data['User_Score'].astype(float) # переводим оценку пользователей в float

In [16]:
data['Critic_Score'] = data['Critic_Score'].astype(int) # переводим оценку критиков в int

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6747 entries, 0 to 16706
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6747 non-null   object
 1   Platform         6747 non-null   object
 2   Year_of_Release  6747 non-null   int32
 3   Genre            6747 non-null   object
 4   Critic_Score     6747 non-null   int32
 5   User_Score       6747 non-null   float64
 6   Rating           6747 non-null   object
dtypes: float64(1), int32(2), object(4)
memory usage: 369.0+ KB

In [19]:
data.sample(30)

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
1435,MotorStorm: Pacific Rift,PS3,2008,Racing,82,8.0,T
5456,WWE Wrestlemania XIX,GC,2003,Fighting,76,8.7,T
12594,Commandos: Strike Force,PS2,2006,Shooter,58,8.5,T
1637,Mario Power Tennis,GC,2004,Sports,80,8.5,E
8766,DiRT 3,PC,2011,Racing,86,6.9,T
3169,Lemony Snicket's A Series of Unfortunate Events,PS2,2004,Platform,63,5.7,E
1509,Yoshi's Woolly World,WiiU,2015,Platform,78,8.5,E
1026,The Order: 1886,PS4,2015,Shooter,63,6.6,M
14840,Age of Conan: Rise of the Godslayer,PC,2010,Role-Playing,83,8.4,M
921,NBA 2K17,PS4,2016,Sports,88,6.7,E
4751,BlazBlue: Continuum Shift,PS3,2010,Fighting,87,8.0,T
9903,Marvel Avengers: Battle for Earth,WiiU,2012,Action,50,5.0,T
7871,Transworld Surf,PS2,2002,Sports,76,8.5,T
3717,Hotel Dusk: Room 215,DS,2007,Adventure,78,8.6,T
3492,Tony Hawk's Pro Skater 4,GBA,2002,Sports,85,8.8,E
961,Namco Museum,PS2,2001,Misc,72,6.0,E
14482,Neverwinter Nights,PC,2002,Role-Playing,91,8.2,T
4461,Eternal Sonata,PS3,2008,Role-Playing,80,7.8,T
3627,WWF Raw,XB,2002,Fighting,68,6.6,T
4333,Shin Megami Tensei: Persona 3,PS2,2006,Role-Playing,86,8.4,M
12763,Blade Dancer: Lineage of Light,PSP,2006,Role-Playing,60,6.9,E10+
13222,Payday 2,PC,2013,Shooter,79,3.4,M
497,Sonic Mega Collection Plus,PS2,2004,Misc,73,8.6,E
16400,TimeShift,PC,2007,Shooter,71,7.6,M
15905,Dark Void,PC,2010,Action,57,5.1,T
3094,F-Zero GX,GC,2003,Racing,89,8.5,T
241,Madden NFL 07,PS2,2006,Sports,84,8.2,E
3614,MX 2002 Featuring Ricky Carmichael,PS2,2001,Racing,76,8.3,E
5026,Dawn of Discovery,PC,2009,Simulation,82,8.8,T
15485,RollerCoaster Tycoon World,PC,2016,Simulation,43,2.4,E

In [23]:
data.describe(include = 'all')

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
count,6747,6747,6747.000000,6747,6747.000000,6747.000000,6747
unique,4307,17,NaN,12,NaN,NaN,6
top,LEGO Star Wars II: The Original Trilogy,PS2,NaN,Action,NaN,NaN,T
freq,8,1140,NaN,1619,NaN,NaN,2338
mean,NaN,NaN,2007.552245,NaN,70.128502,7.171543,NaN
std,NaN,NaN,4.091858,NaN,13.831573,1.439188,NaN
min,NaN,NaN,2000.000000,NaN,13.000000,0.500000,NaN
25%,NaN,NaN,2004.000000,NaN,62.000000,6.500000,NaN
50%,NaN,NaN,2007.000000,NaN,72.000000,7.500000,NaN
75%,NaN,NaN,2011.000000,NaN,80.000000,8.200000,NaN
max,NaN,NaN,2016.000000,NaN,98.000000,9.600000,NaN

In [24]:
# сохранение измененный файл в новый файл Norm_games.h5
data.to_hdf('Norm_games.h5', key='data', mode='a')

In [25]:
# проверка корректности записи файла
new_hdf = pd.read_hdf('Norm_games.h5')
new_hdf

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006,Sports,76,8.0,E
2,Mario Kart Wii,Wii,2008,Racing,82,8.3,E
3,Wii Sports Resort,Wii,2009,Sports,80,8.0,E
6,New Super Mario Bros.,DS,2006,Platform,89,8.5,E
7,Wii Play,Wii,2006,Misc,58,6.6,E
...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,GBA,2001,Action,46,2.4,E
16677,Mortal Kombat: Deadly Alliance,GBA,2002,Fighting,81,8.8,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,80,7.6,M
16700,Breach,PC,2011,Shooter,61,5.8,T
16706,STORM: Frontline Nation,PC,2011,Strategy,60,7.2,E10+

In [26]:
new_hdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6747 entries, 0 to 16706
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6747 non-null   object
 1   Platform         6747 non-null   object
 2   Year_of_Release  6747 non-null   int32
 3   Genre            6747 non-null   object
 4   Critic_Score     6747 non-null   int32
 5   User_Score       6747 non-null   float64
 6   Rating           6747 non-null   object
dtypes: float64(1), int32(2), object(4)
memory usage: 369.0+ KB

In [27]:
new_hdf.sample(30)

,Name,Platform,Year_of_Release,Genre,Critic_Score,User_Score,Rating
3370,NHL 15,PS4,2014,Sports,60,3.6,E10+
7955,Major League Baseball 2K10,PS3,2010,Sports,74,5.3,E
16396,Goat Simulator,XOne,2016,Simulation,53,6.3,T
8914,Blazing Angels 2: Secret Missions of WWII,PS3,2007,Simulation,70,7.2,T
14274,The Sum of All Fears,GC,2003,Shooter,36,3.4,T
6494,MLB 09: The Show,PSP,2009,Sports,78,6.9,E
306,The Legend of Zelda: Skyward Sword,Wii,2011,Action,93,8.0,E10+
7098,The Polar Express,PS2,2004,Adventure,39,4.3,E
2976,NCAA Football 2005,XB,2004,Sports,89,8.0,E
1282,Resistance 3,PS3,2011,Shooter,83,7.8,M
12334,Mario vs. Donkey Kong: Tipping Stars,3DS,2015,Puzzle,70,7.5,E
3924,The BIGS,PS2,2007,Sports,71,4.8,E
3728,Over the Hedge,PS2,2006,Platform,58,8.6,E10+
2917,Lego Star Wars: The Force Awakens,PS4,2016,Action,78,7.5,E10+
3298,Half-Life 2,XB,2005,Shooter,90,8.6,M
15810,East India Company,PC,2009,Strategy,67,5.7,T
5952,MySims SkyHeroes,Wii,2010,Action,67,5.2,E10+
7294,Over G Fighters,X360,2006,Simulation,49,6.0,T
4884,NBA Jam,PS3,2010,Sports,71,5.7,E
15871,Pirates of the Burning Sea,PC,2008,Role-Playing,76,7.6,T
8537,Fatal Frame II: Crimson Butterfly,PS2,2003,Action,81,9.2,M
10585,Agatha Christie: The ABC Murders,DS,2009,Adventure,53,6.5,T
3966,R.U.S.E.,PS3,2010,Strategy,76,7.3,T
5150,Scribblenauts: Unlimited,WiiU,2012,Action,73,7.4,E10+
10998,Beowulf: The Game,PSP,2007,Action,44,5.4,M
5313,Chicken Shoot,Wii,2007,Action,27,4.8,E10+
5545,EA Playground,DS,2007,Sports,60,7.6,E
5341,Tiger Woods PGA Tour 12: The Masters,Wii,2011,Sports,85,6.7,E
7409,Cursed Mountain,Wii,2009,Adventure,67,7.6,M
8519,Return to PopoloCrois: A Story of Seasons Fair...,3DS,2015,Simulation,72,6.8,E10+

In [28]:
new_hdf['Genre'].value_counts()

Action          1619
Sports           941
Shooter          859
Role-Playing     691
Racing           575
Platform         397
Misc             382
Fighting         369
Simulation       291
Strategy         262
Adventure        245
Puzzle           116
Name: Genre, dtype: int64

In [29]:
new_hdf['Rating'].value_counts()

T       2338
E       2058
M       1420
E10+     929
RP         1
AO         1
Name: Rating, dtype: int64

In [30]:
new_hdf['Platform'].value_counts()

PS2     1140
X360     858
PS3      769
PC       641
XB       565
Wii      479
DS       464
PSP      390
GC       348
PS4      239
GBA      237
XOne     159
3DS      155
PSV      118
WiiU      89
PS        85
DC        11
Name: Platform, dtype: int64